import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#04052B',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 32,
    paddingBottom: 32, 
    width: '100%',
  },
  safeAreaContainer: { 
    flex: 1,
    backgroundColor: '#04052B',
    width: '100%',
  },
  scrollContentContainer: { 
    alignItems: 'center', 
    paddingTop: 32,
    paddingBottom: 64,
  },
  listItemContainer: { 
    marginBottom: 40,
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  sobreContent: { 
    alignItems: 'center',
    paddingHorizontal: 20, 
    paddingTop: 0, 
    paddingBottom: 40,
  },
  title: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 32,
    textAlign: 'center',
    marginTop: 16,
    marginBottom: 32,
  },
  subtitle: {
    color: '#A2A6B0',
    fontSize: 20,
    textAlign: 'center',
    marginBottom: 32,
  },
  iconsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 24,
    marginVertical: 16,
    flexWrap: 'wrap',
    width: '100%',
    maxWidth: 360,
  },
  iconCircle: {
    backgroundColor: '#26213C',
    borderRadius: 30,
    padding: 12,
    marginHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatar: {
    width: 200,
    height: 200,
    borderRadius: 100,
    marginTop: 24,
    marginBottom: 20,
  },
  button: {
    position: 'absolute',
    bottom: 80,
    left: '12.5%',
    width: '75%',
    backgroundColor: '#02031C',
    borderColor: '#FFFFFF',
    borderWidth: 1,
    paddingVertical: 12,
    borderRadius: 35,
    alignItems: 'center',
    zIndex: 10,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  subtext: {
    color: '#A2A6B0',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 32,
    marginHorizontal: 16,
    lineHeight: 24,
  },
  iconImage: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    maxWidth: 48,
    maxHeight: 48,
  },
  carouselCard: {
    backgroundColor: '#04052B',
    borderRadius: 16,
    alignItems: 'center',
  },
  carouselImage: {
    borderRadius: 16,
    borderWidth: 0,
    borderColor: 'transparent',
    resizeMode: 'cover',
  },
  carouselTextContainer:{
    marginTop: 8,
    paddingHorizontal: 12, 
    width: '100%',
  },
  carouselTitle: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 20,
    textAlign: 'left',
  },
  carouselSubtitle: {
    color: ' #fff',
    opacity: 0.8,
    marginBottom: 0,
    textAlign: 'left',
  },
  descBox: {
    backgroundColor: '#22254B',
    borderRadius: 12,
    marginTop: 12,
    padding: 14,
    width: '100%',
  },
  carouselDesc: {
    color: '#fff',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'left',
  },
});